# Generated by Django 3.2.2 on 2021-05-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countyId', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFilters',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('notVegan', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('barley', models.BooleanField(default=False)),
                ('peanut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('buckwheat', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('oats', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('sulphites', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('manId', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=999)),
                ('stock', models.IntegerField()),
                ('isFood', models.BooleanField()),
                ('manId', models.ManyToManyField(to='ship_o_cereal.Manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('typeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('productId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ship_o_cereal.products')),
                ('nutritionLabel', models.CharField(max_length=999, null=True)),
                ('notVegan', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('barley', models.BooleanField(default=False)),
                ('peanut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('buckwheat', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('oats', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('sulphites', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='typeId',
            field=models.ManyToManyField(to='ship_o_cereal.ProductTypes'),
        ),
        migrations.CreateModel(
            name='Creditcards',
            fields=[
                ('cardId', models.BigAutoField(primary_key=True, serialize=False)),
                ('cardname', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=16)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('review', models.CharField(max_length=500)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartRows',
            fields=[
                ('cartRowId', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.carts')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.products')),
            ],
        ),
        migrations.CreateModel(
            name='CartFolio',
            fields=[
                ('folioId', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('addrId', models.BigAutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('apt_num', models.IntegerField(null=True)),
                ('zip', models.IntegerField()),
                ('countryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.countries')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('cartId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ship_o_cereal.carts')),
                ('date', models.DateField()),
                ('addrId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ship_o_cereal.addresses')),
                ('cardId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ship_o_cereal.creditcards')),
            ],
        ),
    ]
