# Generated by Django 3.2.2 on 2021-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='aaa@gmail.com', max_length=500),
            preserve_default=False,
        ),
    ]
