# Generated by Django 3.2.2 on 2021-05-13 11:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0002_alter_countries_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='countryId',
        ),
        migrations.AddField(
            model_name='addresses',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
