# Generated by Django 3.2.2 on 2021-05-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0002_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='cardNumber',
            field=models.CharField(max_length=16),
        ),
    ]
