# Generated by Django 3.2.2 on 2021-05-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0003_auto_20210513_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
