# Generated by Django 3.2.2 on 2021-05-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0004_alter_comments_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.users'),
        ),
    ]
