# Generated by Django 3.2.2 on 2021-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='town',
            field=models.CharField(default='reykjavík', max_length=255),
            preserve_default=False,
        ),
    ]
