# Generated by Django 3.2.2 on 2021-05-12 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ship_o_cereal', '0006_auto_20210511_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartFolio',
            fields=[
                ('folioId', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
