# Generated by Django 3.2.2 on 2021-05-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0006_addresses_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrients',
            name='barley',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='buckwheat',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='gluten',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='maize',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='notVegan',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='nutritionLabel',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='oats',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='peanut',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='rice',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='sesame',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='soy',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='sulphites',
        ),
        migrations.RemoveField(
            model_name='nutrients',
            name='wheat',
        ),
    ]
