# Generated by Django 3.2.2 on 2021-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0007_auto_20210514_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrients',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrients',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nutrients',
            name='ingredients',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='nutrients',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
