# Generated by Django 3.2.2 on 2021-05-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0007_cartfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countyId', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='addresses',
            name='apt_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creditcards',
            name='cardname',
            field=models.CharField(default='jcnoen', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='countryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ship_o_cereal.countries'),
            preserve_default=False,
        ),
    ]
