# Generated by Django 3.2.2 on 2021-05-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_o_cereal', '0009_auto_20210512_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='street',
            new_name='address',
        ),
    ]
