# Generated by Django 3.2.1 on 2021-05-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFilters',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.users')),
                ('notVegan', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('barley', models.BooleanField(default=False)),
                ('peanut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('sulphites', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('mustard', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('oats', models.BooleanField(default=False)),
                ('garlic', models.BooleanField(default=False)),
                ('kiwi', models.BooleanField(default=False)),
                ('mango', models.BooleanField(default=False)),
                ('strawberry', models.BooleanField(default=False)),
                ('banana', models.BooleanField(default=False)),
                ('avocado', models.BooleanField(default=False)),
                ('tomato', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('buckwheat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('productId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.products')),
                ('nutritionLabel', models.CharField(max_length=999, null=True)),
                ('notVegan', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('wheat', models.BooleanField(default=False)),
                ('barley', models.BooleanField(default=False)),
                ('peanut', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('sulphites', models.BooleanField(default=False)),
                ('sesame', models.BooleanField(default=False)),
                ('rice', models.BooleanField(default=False)),
                ('mustard', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('maize', models.BooleanField(default=False)),
                ('oats', models.BooleanField(default=False)),
                ('garlic', models.BooleanField(default=False)),
                ('kiwi', models.BooleanField(default=False)),
                ('mango', models.BooleanField(default=False)),
                ('strawberry', models.BooleanField(default=False)),
                ('banana', models.BooleanField(default=False)),
                ('avocado', models.BooleanField(default=False)),
                ('tomato', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('pineapple', models.BooleanField(default=False)),
                ('buckwheat', models.BooleanField(default=False)),
            ],
        ),
    ]
