# Generated by Django 3.2.1 on 2021-05-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('typeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('banned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=999)),
                ('stock', models.IntegerField()),
                ('isFood', models.BooleanField()),
                ('typeId', models.ManyToManyField(to='store.ProductTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Creditcards',
            fields=[
                ('cardId', models.BigAutoField(primary_key=True, serialize=False)),
                ('cardNumber', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('review', models.CharField(max_length=500)),
                ('productId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='CartRows',
            fields=[
                ('cartRowId', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carts')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('addrId', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('cartId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.carts')),
                ('date', models.DateField()),
                ('addrId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.addresses')),
                ('cardId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.creditcards')),
            ],
        ),
    ]
