# Generated by Django 3.2.1 on 2021-05-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('manId', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='manId',
            field=models.ManyToManyField(to='store.Manufacturers'),
        ),
    ]
